package com._1easy.hashtables;

/**
 * 389
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 * <p>
 * Example 1:
 * <p>
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 */
public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifferenceTwo("abcd", "abcde"));
    }

    // 1ms, Beats 99%
    public static char findTheDifference(String s, String t) {

        int sSum = 0;
        for(char letter : s.toCharArray()) {
            sSum += letter;
        }

        int tSum = 0;
        for(char letter : t.toCharArray()) {
            tSum += letter;
        }

        return (char) (tSum - sSum);
    }

    // 2ms, Beats 62%
    public static char findTheDifferenceTwo(String s, String t) {

        int[] sArr = new int[26];
        for(char letter : s.toCharArray()) {
            sArr[letter - 'a']++;
        }

        int[] tArr = new int[26];
        for(char letter : t.toCharArray()) {
            tArr[letter - 'a']++;
        }

        char answer = ' ';

        for(int i = 0 ; i < 26; i++) {
            int sVal = sArr[i];
            int tVal = tArr[i];

            if(tVal > sVal) answer = (char) (i + 'a');
        }

        return answer;
    }

}
